import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Box Office Buddies",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body>
        <Navbar user={session?.user} />
        {children}
      </body>
    </html>
  );
}
